name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: welcome message 
          run: |
            echo "welcome to actions"
            ls -ltra
            cat README.md
        
        - name: Generate ASCII artwork
          run:  cowsay -f dragon "hello dosto" >> dragon.txt



